<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="MSI" failures="1" tests="6" name="TestPage.TestDashboard.TestDatabase" time="19.240" errors="0" timestamp="2019-12-17T22:29:09 GMT+03:00" skipped="5">
  <testcase classname="TestPage.TestDashboard.TestDatabase" name="suiteSetUp" time="19.240">
    <failure message="Alert not displayed did not expect to find [false] but found [true]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Alert not displayed did not expect to find [false] but found [true]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertFalse(Assert.java:65)
at TestPage.EnvContainer.Registration(EnvContainer.java:101)
at TestPage.EnvContainer.suiteSetUp(EnvContainer.java:58)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:340)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:294)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:345)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
    </failure>
  </testcase> <!-- suiteSetUp -->
  <testcase classname="TestPage.TestDashboard.TestDatabase" name="testHome" time="0.000">
    <skipped/>
  </testcase> <!-- testHome -->
  <testcase classname="TestPage.TestDashboard.TestDatabase" name="testHome2" time="0.000">
    <skipped/>
  </testcase> <!-- testHome2 -->
  <testcase classname="TestPage.TestDashboard.TestDatabase" name="testHome3" time="0.000">
    <skipped/>
  </testcase> <!-- testHome3 -->
  <testcase classname="TestPage.TestDashboard.TestDatabase" name="testHome4" time="0.000">
    <skipped/>
  </testcase> <!-- testHome4 -->
  <testcase classname="TestPage.TestDashboard.TestDatabase" name="testHome5NeNorm" time="0.000">
    <skipped/>
  </testcase> <!-- testHome5NeNorm -->
</testsuite> <!-- TestPage.TestDashboard.TestDatabase -->
